Compute opti dijkstra
lhexanome/Optimod-livraison pull request #70
Opened 2017-10-26 19:39 UTC by Arkmut

2017-10-26 19:44 UTC, Arkmut commented
le pire coverage du monde^^

2017-10-26 19:45 UTC, Embraser01 commented
Après ce que je lui est mis tout à l'heure avec ma PR, je te rassure c'est bien 😃

2017-10-26 19:57 UTC, Embraser01 requested changes
Je te laisserais modifier les différentes review avant de la valider :)

2017-10-26 19:57 UTC, Embraser01 commented on platform/src/main/java/lhexanome/optimodlivraison/platform/compute/IntersectionWrapper.java
> +    private Vector cheminArrivant;
Tu peux changer le nom en une version anglaise ?

2017-10-26 19:57 UTC, Embraser01 commented on platform/src/main/java/lhexanome/optimodlivraison/platform/compute/IntersectionWrapper.java
> +    private Vector cheminArrivant;
Un `MAJ + F6` sera très rapide

2017-10-26 19:57 UTC, Embraser01 commented on platform/src/main/java/lhexanome/optimodlivraison/platform/compute/SimplifiedMap.java
> +                                             ArrayList<Path> sortie) {
Pareil ici (j'en ai loupé d'autres) 😄 Je le redis ici, mais si on mélange Anglais/Français dans le code, on va vite se perdre

2017-10-26 19:57 UTC, Embraser01 commented on platform/src/main/java/lhexanome/optimodlivraison/platform/compute/SimplifiedMap.java
>      public java.util.Map getGraph() {
Lors de mon refactoring, j'ai foiré les imports et du coup on trouve ça parfois... Faudrait l'enlevé et rajouter les types de la Map (ex: `Map<Long, String>`)

2017-10-26 19:57 UTC, Embraser01 commented on platform/src/main/java/lhexanome/optimodlivraison/platform/models/Path.java
> +    public Path(Halt begin, Halt end) {
Le début c'est pas toujours un entrepot ?

2017-10-26 19:57 UTC, Embraser01 commented on platform/src/test/java/lhexanome/optimodlivraison/platform/compute/SimplifiedMapTest.java
> +        assertThat(sm).isEqualTo(sm);
Egale à lui même ? Il y a un problème :)

2017-10-26 19:57 UTC, Embraser01 commented on platform/src/test/java/lhexanome/optimodlivraison/platform/models/PathTest.java
>          path35.addTroncon(vector45);
Les asserts dans la suite sont inutile, si tu veux faire fail un test, tu peux appeler la fonction `fail("Mon message d'echec de test")`

2017-10-26 20:00 UTC, Arkmut commented on platform/src/main/java/lhexanome/optimodlivraison/platform/models/Path.java
> +    public Path(Halt begin, Halt end) {
non, vu que mon graphe simplifié peut avoir des trajets entre 2 pts de livraisons qcques

2017-10-26 20:01 UTC, Arkmut commented on platform/src/test/java/lhexanome/optimodlivraison/platform/compute/SimplifiedMapTest.java
> +        assertThat(sm).isEqualTo(sm);
oui c'est un pseudo test, je m'en suis servi pour pourvoir lancer un debug. c'est trop long de rentrer à la main tout les trucs qu'il est sensé avoir..

2017-10-26 20:01 UTC, Embraser01 commented on platform/src/main/java/lhexanome/optimodlivraison/platform/models/Path.java
> +    public Path(Halt begin, Halt end) {
Ok, très bien :)

2017-10-26 20:02 UTC, Embraser01 commented on platform/src/test/java/lhexanome/optimodlivraison/platform/compute/SimplifiedMapTest.java
> +        assertThat(sm).isEqualTo(sm);
Ok d'acc, moyen de modifier avant de merge ? Ou de mettre un `// TODO` pour pas qu'on oublie ?

2017-10-26 20:03 UTC, Arkmut commented on platform/src/test/java/lhexanome/optimodlivraison/platform/models/PathTest.java
>          path35.addTroncon(vector45);
ok la je sais pas trop, j'ai juste adapté comme je pouvais les tests existants à ma modif de path

2017-10-26 20:08 UTC, Embraser01 commented on platform/src/test/java/lhexanome/optimodlivraison/platform/models/PathTest.java
>          path35.addTroncon(vector45);
Pas de soucis, les `assertTrue(true)` sont pas utile par exemple et peuvent être enlevé :)

2017-10-27 06:00 UTC, Embraser01 approved these changes

2017-10-27 06:00 UTC, merged