Ihm click intersection
lhexanome/Optimod-livraison pull request #87
Opened 2017-10-31 20:53 UTC by Natibus

J'ai corrigé le style et ajouté un icône vert.
Le redimensionnement arrivera sous peu :)

2017-10-31 21:07 UTC, Embraser01 requested changes
Globalement c'est cool 😎 Je te laisse faire les modifications que j'ai mises, et oublie pas de lancer une fois avec intellij avant de commit :D

2017-10-31 21:07 UTC, Embraser01 commented on ui/src/main/java/lhexanome/optimodlivraison/ui/component/RoadMapComponent.java
> +    private final double imageScale = 0.5;
Si tu l'utilises uniquement en tant que constante, faudrait la mettre en `static` et l'appeller `IMAGE_SCALE` 😃

2017-10-31 21:07 UTC, Embraser01 commented on ui/src/main/java/lhexanome/optimodlivraison/ui/controller/RoadMapController.java
> +    private final double maxDistance = 1000000000;
Si c'est pour avoir la plus grande valeur possible, tu peux utiliser `Double.MAX_VALUE`

2017-10-31 21:07 UTC, Embraser01 commented on ui/src/main/java/lhexanome/optimodlivraison/ui/controller/RoadMapController.java
> +    public Intersection getClosestIntersection(int xMouse, int yMouse) {
La fonction serait pas mieux dans `RoadMapComponent` ? Ou il y avait une raison pour la mettre dans le controller ?

2017-10-31 21:07 UTC, Embraser01 commented on ui/src/main/java/lhexanome/optimodlivraison/ui/panel/RoadMapPanel.java
> +        $$$setupUI$$$();
Faut enlever ça, c'est mis automatiquement par intellij (bien vérifier la config Intellij : 
> File > Editor > GUI designer > Java source)

2017-10-31 21:44 UTC, Embraser01 commented on ui/src/main/java/lhexanome/optimodlivraison/ui/controller/RoadMapController.java
> +        currentIntersection = getClosestIntersection(xMouse, yMouse);
Tu verras dans #86, j'ai ajouté des méthodes pour notifier d'une selection. Dès qu'on fusionne les deux, ça devrait marcher dans les deux sens (faudrait faire une fonction public dans `RoadMapComponent` pour centrer sur un point (cc @loicsrz )

2017-11-01 08:26 UTC, Natibus commented on ui/src/main/java/lhexanome/optimodlivraison/ui/component/RoadMapComponent.java
> +    private final double imageScale = 0.5;
D'acc, je m'en occupe :+1:

2017-11-01 08:42 UTC, Natibus commented on ui/src/main/java/lhexanome/optimodlivraison/ui/controller/RoadMapController.java
> +    public Intersection getClosestIntersection(int xMouse, int yMouse) {
Il fallait faire remonter les opérations au controlleur non ? De plus, Loïc a besoin de getClosestIntesection ^^

2017-11-01 10:29 UTC, Embraser01 commented on ui/src/main/java/lhexanome/optimodlivraison/ui/controller/RoadMapController.java
> +    public Intersection getClosestIntersection(int xMouse, int yMouse) {
Quand je parlais de faire remonter au controller c'est juste l'information de l'intersection selectionnée. 
Tu fais tout le calcul dans le `RoadMapComponent`, et ensuite tu notifies au controller que une intersection a été selectionnée. La recherche de l'intersection la plus proche du clique reste dans le composant

2017-11-03 14:56 UTC, Embraser01 approved these changes

2017-11-03 14:56 UTC, merged